package org.clappa.app
// Generated by tools/generate-prompts.mjs.
internal object Prompts {
 private val all=mapOf(
  "left" to "Take a picture to your left!",
  "right" to "Take a picture to your right!",
  "selfie" to "Take a selfie!",
  "up" to "Take a picture above you!",
  "down" to "Take a picture below you!",
  "front" to "Take a picture in front of you!",
  "back" to "Take a picture behind you!",
  "recording_camera" to "Photograph the recording camera!",
  "main_subject_alt_angle" to "Show your subject from another angle!",
  "room_setup" to "Take a picture of your setup!",
  "selfie_cover_left" to "Cover your left eye with your left hand!",
  "selfie_cover_right" to "Cover your right eye with your right hand!",
  "selfie_wink" to "Hold a wink for both photos!",
  "selfie_turn" to "Turn your face slightly to one side!",
  "selfie_left" to "Turn to your left and take a selfie!",
  "selfie_right" to "Turn to your right and take a selfie!",
  "selfie_around" to "Face the other way and take a selfie!",
  "selfie_nose_left" to "Cover your nose with your left hand!",
  "selfie_nose_right" to "Cover your nose with your right hand!",
  "selfie_chin" to "Rest your chin on your hand!",
  "selfie_palm" to "Hold an open hand beside your face!",
  "selfie_smile" to "Give us a smile!",
  "selfie_tilt" to "Tilt your head to one side!"
 )
 private val dual=mapOf(
  "selfie" to "Show yourself and your setup!",
  "selfie_cover_left" to "Cover your left eye · show your setup!",
  "selfie_cover_right" to "Cover your right eye · show your setup!",
  "selfie_wink" to "Hold a wink · show your setup!",
  "selfie_turn" to "Turn your face · show your setup!",
  "selfie_left" to "Turn to your left and take a selfie!",
  "selfie_right" to "Turn to your right and take a selfie!",
  "selfie_around" to "Face the other way and take a selfie!",
  "selfie_nose_left" to "Cover your nose with your left hand!",
  "selfie_nose_right" to "Cover your nose with your right hand!",
  "selfie_chin" to "Rest your chin on your hand!",
  "selfie_palm" to "Hold an open hand beside your face!",
  "selfie_smile" to "Give us a smile!",
  "selfie_tilt" to "Tilt your head to one side!"
 )
 fun text(id:String,both:Boolean=false)=(if(both)dual else all)[id]?:error("Unknown prompt")
}
