package org.clappa.app
import android.content.Context
import org.json.JSONObject
import org.json.JSONArray

/** Validator for the exact schema vocabulary generated by protocol/schema.mjs. */
internal class ProofSchema(ctx:Context){
 private val root=ctx.assets.open("proof-schema.json").bufferedReader().use{JSONObject(it.readText())}
 fun requireValid(kind:String,value:JSONObject){require(valid(root.getJSONObject("definitions").getJSONObject(kind),value)){"Unsupported or malformed $kind fields"}}
 private fun valid(s:JSONObject,v:Any):Boolean {
  if(s.has("\$ref")){val ref=s.getString("\$ref");require(ref.startsWith("#/definitions/"));return valid(root.getJSONObject("definitions").getJSONObject(ref.removePrefix("#/definitions/")),v)}
  if(s.has("const")&&Proof.canonical(s.get("const"))!=Proof.canonical(v))return false
  s.optJSONArray("enum")?.let{a->if((0 until a.length()).none{Proof.canonical(a.get(it))==Proof.canonical(v)})return false}
  for(k in listOf("oneOf","anyOf"))s.optJSONArray(k)?.let{a->val n=(0 until a.length()).count{valid(a.getJSONObject(it),v)};if(n==0||k=="oneOf"&&n!=1)return false}
  when(s.optString("type")){
   "object"->{if(v !is JSONObject)return false;val required=s.optJSONArray("required")?:JSONArray();if((0 until required.length()).any{!v.has(required.getString(it))})return false;val props=s.optJSONObject("properties")?:JSONObject();for(k in v.keys()){if(props.has(k)){if(!valid(props.getJSONObject(k),v.get(k)))return false}else if(!s.optBoolean("additionalProperties",true))return false}}
   "array"->{if(v !is JSONArray||v.length()<s.optInt("minItems",0)||v.length()>s.optInt("maxItems",1000))return false;for(i in 0 until v.length())if(!valid(s.getJSONObject("items"),v.get(i)))return false}
   "string"->{if(v !is String||v.length>s.optInt("maxLength",131072))return false;if(s.has("pattern")&&!Regex(s.getString("pattern")).containsMatchIn(v))return false}
   "integer"->{if(v !is Int&&v !is Long)return false;val n=(v as Number).toLong();if(n<s.optLong("minimum",-9007199254740991L)||n>s.optLong("maximum",9007199254740991L))return false}
   "boolean"->if(v !is Boolean)return false
   "null"->if(v!==JSONObject.NULL)return false
   ""->{}
   else->error("Unsupported schema type")
  };return true
 }
}
