#pragma once
#include <QString>
#include <string>
#include <stdexcept>
// Generated by tools/generate-prompts.mjs.
inline QString promptText(const std::string &id,bool both=false){
 if(both){
 if(id=="selfie")return QStringLiteral("Show yourself and your setup!");
 if(id=="selfie_cover_left")return QStringLiteral("Cover your left eye · show your setup!");
 if(id=="selfie_cover_right")return QStringLiteral("Cover your right eye · show your setup!");
 if(id=="selfie_wink")return QStringLiteral("Hold a wink · show your setup!");
 if(id=="selfie_turn")return QStringLiteral("Turn your face · show your setup!");
 if(id=="selfie_left")return QStringLiteral("Turn to your left and take a selfie!");
 if(id=="selfie_right")return QStringLiteral("Turn to your right and take a selfie!");
 if(id=="selfie_around")return QStringLiteral("Face the other way and take a selfie!");
 if(id=="selfie_nose_left")return QStringLiteral("Cover your nose with your left hand!");
 if(id=="selfie_nose_right")return QStringLiteral("Cover your nose with your right hand!");
 if(id=="selfie_chin")return QStringLiteral("Rest your chin on your hand!");
 if(id=="selfie_palm")return QStringLiteral("Hold an open hand beside your face!");
 if(id=="selfie_smile")return QStringLiteral("Give us a smile!");
 if(id=="selfie_tilt")return QStringLiteral("Tilt your head to one side!");
 throw std::runtime_error("Unknown dual prompt");
 }
 if(id=="left")return QStringLiteral("Take a picture to your left!");
 if(id=="right")return QStringLiteral("Take a picture to your right!");
 if(id=="selfie")return QStringLiteral("Take a selfie!");
 if(id=="up")return QStringLiteral("Take a picture above you!");
 if(id=="down")return QStringLiteral("Take a picture below you!");
 if(id=="front")return QStringLiteral("Take a picture in front of you!");
 if(id=="back")return QStringLiteral("Take a picture behind you!");
 if(id=="recording_camera")return QStringLiteral("Photograph the recording camera!");
 if(id=="main_subject_alt_angle")return QStringLiteral("Show your subject from another angle!");
 if(id=="room_setup")return QStringLiteral("Take a picture of your setup!");
 if(id=="selfie_cover_left")return QStringLiteral("Cover your left eye with your left hand!");
 if(id=="selfie_cover_right")return QStringLiteral("Cover your right eye with your right hand!");
 if(id=="selfie_wink")return QStringLiteral("Hold a wink for both photos!");
 if(id=="selfie_turn")return QStringLiteral("Turn your face slightly to one side!");
 if(id=="selfie_left")return QStringLiteral("Turn to your left and take a selfie!");
 if(id=="selfie_right")return QStringLiteral("Turn to your right and take a selfie!");
 if(id=="selfie_around")return QStringLiteral("Face the other way and take a selfie!");
 if(id=="selfie_nose_left")return QStringLiteral("Cover your nose with your left hand!");
 if(id=="selfie_nose_right")return QStringLiteral("Cover your nose with your right hand!");
 if(id=="selfie_chin")return QStringLiteral("Rest your chin on your hand!");
 if(id=="selfie_palm")return QStringLiteral("Hold an open hand beside your face!");
 if(id=="selfie_smile")return QStringLiteral("Give us a smile!");
 if(id=="selfie_tilt")return QStringLiteral("Tilt your head to one side!");
 throw std::runtime_error("Unknown prompt");
}
