import fs from 'node:fs/promises';
const dir='docs/review8';
await fs.copyFile('output/qr-review8-camera/results.json',dir+'/qr-camera-results.json');
await fs.copyFile('output/native-render.png',dir+'/obs-fixture.png');
await fs.copyFile('output/native-flash-preview.png',dir+'/obs-flash-fixture.png');
const flow=JSON.parse(await fs.readFile(dir+'/emulator-flow-result.json'));
let tests=0,failures=0;
for(const file of await fs.readdir('android/app/build/test-results/testDebugUnitTest'))if(file.endsWith('.xml')){
 const s=await fs.readFile('android/app/build/test-results/testDebugUnitTest/'+file,'utf8');tests+=Number(s.match(/tests="(\d+)"/)[1]);failures+=Number(s.match(/failures="(\d+)"/)[1]);
}
if(failures||flow.result.status!=='EXACT ORIGINAL VERIFIED')throw Error('Validation incomplete');
await fs.writeFile(dir+'/validation.json',JSON.stringify({androidUnitTests:{tests,failures},nativeScreens:{normal:12,enlargedTextCutoutThreeButton:9},cameraFlow:flow.result.status,captureGapsMs:flow.captures.map(c=>c.gapMs),nativeIntegration:['two successive recordings independently sealed with the same pairing','all QR frames decode at identical bounds','Photo B initially visible then fades to A','QR motion-freeze timing checks passed'],tls:JSON.parse(await fs.readFile(dir+'/tls-results.json')),iterations:['widened gap between landscape controls and bubble after screenshot inspection','kept End session stationary when six-second photo offer expires','confined TLS to one worker after observing bad-record-MAC with concurrent TLS on a non-threaded Mbed TLS build'],limitations:['Emulator camera does not validate physical illumination','Local x264 probes, not streaming-platform certification','360p QR recovery failed','Packet archives are not yet independently matched against muxed recording packets']},null,2));
const p='protocol/README.md';let protocol=await fs.readFile(p,'utf8');if(!protocol.includes('single TLS worker'))await fs.writeFile(p,protocol+'\n## Windows TLS execution (Test8)\n\nThe bundled Mbed TLS 3.6.4 build lacks `MBEDTLS_THREADING_C`. The native HTTP server uses a single TLS worker, bounded queue and one request per connection, preventing simultaneous access to its shared TLS/PSA state. TLS 1.3, certificate pinning and bearer authentication remain enforced. Legacy non-PSA signature verification uses a separate context; enabling `MBEDTLS_USE_PSA_CRYPTO` or parallel TLS later requires a properly threaded Mbed TLS build. See [Mbed TLS threading requirements](https://mbed-tls.readthedocs.io/en/latest/kb/development/thread-safety-and-multi-threading/).\n');
const notes='docs/test8.md';let text=await fs.readFile(notes,'utf8');text=text.replace('Test results and limits are linked from that page.','Test results and limits are linked from that page.\n\n- Ten Android unit tests passed; twelve native state/orientation captures and nine enlarged-text/cutout/navigation captures were inspected.\n- The final app completed capture, transfer and final seal: EXACT ORIGINAL VERIFIED, with 1182/1208 ms selfie-pair gaps.\n- The final OBS plugin independently sealed two successive recordings with the same pairing. Every QR frame decoded with identical boundaries; flash crossfade and motion-freeze checks passed.\n- Forty-eight TLS 1.3 requests from six simultaneous clients passed certificate-pin and authentication checks.\n- Local re-encodes recovered both eleven-chunk photo events at 1080p, 720p, 480p and 720p plus 0.6-sigma blur. 360p failed.');await fs.writeFile(notes,text);
console.log({androidTests:tests,failures,flow:flow.result.status});
