import fs from 'node:fs';
const prompts=JSON.parse(fs.readFileSync('protocol/prompts.json')),dual=JSON.parse(fs.readFileSync('protocol/dual-prompts.json'));
const kotlin=m=>Object.entries(m).map(([k,v])=>`  ${JSON.stringify(k)} to ${JSON.stringify(v)}`).join(',\n');
fs.writeFileSync('android/app/src/main/java/org/clappa/app/Prompts.kt',`package org.clappa.app\n// Generated by tools/generate-prompts.mjs.\ninternal object Prompts {\n private val all=mapOf(\n${kotlin(prompts)}\n )\n private val dual=mapOf(\n${kotlin(dual)}\n )\n fun text(id:String,both:Boolean=false)=(if(both)dual else all)[id]?:error("Unknown prompt")\n}\n`);
const cpp=m=>Object.entries(m).map(([k,v])=>` if(id==${JSON.stringify(k)})return QStringLiteral(${JSON.stringify(v)});`).join('\n');
fs.writeFileSync('obs-plugin/src/prompts.h',`#pragma once\n#include <QString>\n#include <string>\n#include <stdexcept>\n// Generated by tools/generate-prompts.mjs.\ninline QString promptText(const std::string &id,bool both=false){\n if(both){\n${cpp(dual)}\n throw std::runtime_error("Unknown dual prompt");\n }\n${cpp(prompts)}\n throw std::runtime_error("Unknown prompt");\n}\n`);
