import fs from 'node:fs/promises';
async function edit(file,fn){const before=await fs.readFile(file,'utf8');const after=fn(before);if(after===before)throw Error('No change: '+file);await fs.writeFile(file,after);}
await edit('obs-plugin/src/native-service.cpp',s=>s.replace('J pub,state,pending,sealRequest;','J pub,state,pending,sealRequest,issuedEvent;').replace('pending=d;pending["at"]','issuedEvent=e;pending=d;pending["at"]').replace('void tile(const J &e,const J &images)','void tile(const J &e,const J &images,const J &context)').replace('{"photos",photos}}.dump()', '{"photos",photos},{"context",context}}.dump()').replace('if(t=="challenge-captured"||t=="claim")tile(e,images);',`if(t=="challenge-captured"||t=="claim"){
    auto context=m.at("context");need(context.size()==2&&context.at("challenge")==issuedEvent,"Wrong challenge context");auto proof=context.at("proof");validate("media-proof",proof);signature(proof);auto v=proof.at("payload");
    need(v["key_id"]==pub["key_id"]&&v["session_id"]==sid&&v["recording_id"]==state["recording_id"]&&v["event_sha256"]==hash(bytes(e.dump()))&&v["challenge_sha256"]==hash(bytes(issuedEvent.dump()))&&v["at"]>=p["at"]&&v["descriptors"]==state["descriptors"],"Media proof does not bind this recording and response");
    for(auto &o:v["outputs"])need(o["packets"].get<long long>()>0,"Empty media prefix");outputs(v["outputs"]);
    save(folder()+QString("/media-proofs/%1.json").arg(count,6,10,QChar('0')),context);tile(e,images,context);
   }`));
await edit('obs-plugin/native-integration-test.mjs',s=>s.replace('let cursor=0,seq=0,head=null,session,outputs,seal', 'let issued,qrFrames;let cursor=0,seq=0,head=null,session,outputs,seal').replace("import {parseTransportFrame}","import {parseTransportFrame}").replace("import https from", "import {verifyQrMedia} from '../verifier/qr-proof.mjs';\nimport https from").replace("await req('/message',{type:'event',event:e,images});head",`let context;if(type==='challenge-issued')issued=e;if(type==='challenge-captured'||type==='claim')context={challenge:issued,proof:signObject({profile:'CLAPPA-MEDIA-PROOF-v1',algorithm:'ES256-P1363',key_id:pub.key_id,session_id:session.session_id,recording_id:session.recording_id,event_sha256:hashObject(e),challenge_sha256:hashObject(issued),at:Date.now(),outputs,descriptors:session.descriptors},privateKey)};await req('/message',{type:'event',event:e,images,...(context?{context}:{})});head`).replace('left:156,top:124','left:24,top:118').replace('for(const file of manifest.frames)', 'qrFrames=[];for(const file of manifest.frames)').replace("if(!qr)throw Error('One QR frame cannot be decoded');", "if(!qr)throw Error('One QR frame cannot be decoded');qrFrames.push(qr.data);").replace("await writeFile('output/native-integration-result.json'", "const prefix=await verifyQrMedia(qrFrames,`${root}/sessions/${session.session_id}/proof`,state.media_path,{trustedKey:pub.key_id});console.log(prefix);\n  await writeFile('output/native-integration-result.json'").replace('JSON.stringify({result,packets:state.outputs', 'JSON.stringify({result,prefix,packets:state.outputs'));
await edit('obs-plugin/src/board-art.h',s=>s.replace('BoardWidth=772','BoardWidth=848').replaceAll('772','848').replace('x<800','x<880').replaceAll('337,246','492,292').replaceAll('65,89','16,80').replace('65+(337-fit.width())/2,89+(246-fit.height())/2','16+(492-fit.width())/2,80+(292-fit.height())/2').replace('p.translate(100,40)','p.translate(12,40)').replace(/ const QImage crown[^\n]+\n/,'').replace(/ p.save\(\);p.setClipRect\(QRectF\(-100[^\n]+\n/,'').replace(/ p.save\(\);p.setClipRect\(QRectF\(0,64[^\n]+\n/,'').replace('770,438','846,438').replace('QRectF(59,84,355,292)','QRectF(12,78,504,304)').replace('QRectF(56,80,355,292)','QRectF(10,74,504,304)').replace('QRectF(194,73,76,18)','QRectF(222,68,76,18)').replace('p.setPen(QColor("#34322c"))','p.setPen(QColor("#f2eee4"))').replace('QRectF(68,338,332,28),Qt::AlignCenter','QRectF(16,380,600,26),Qt::AlignLeft|Qt::AlignVCenter').replace('594-side/2,230-side/2','682-side/2,226-side/2').replace(/ p.save\(\);p.setClipRect\(QRectF\(75,388[^\n]+\n/,'').replace('QRectF(633,397,111,32)','QRectF(717,402,111,32)').replace(',236,401,.72',',16,407,.72').replace('QRectF(577,404,34,22)','QRectF(365,410,34,22)'));
await edit('obs-plugin/src/plugin.cpp',s=>s.replace('if(age<.25){double u=age/.25;y=(BoardArt::Height+53)*std::pow(1-u,3)-3;}else if(age<.36)y=-3*(1-(age-.25)/.11);','if(age<.31){double u=age/.31;double ease=u*u*(3-2*u);y=(BoardArt::Height+53)*(1-ease)-3;}else if(age<.42)y=-3*(1-(age-.31)/.11);').replace('p.translate(100,40)','p.translate(12,40)').replaceAll('New pairing code','Connect another phone').replace('Optional SHA-256 public-key fingerprint','Identity code from your phone (optional)').replace('Trusted phone identity (public key only)','Optional: restrict pairing to your saved identity').replace('new QPushButton("Use fingerprint")','new QPushButton("Save identity restriction")').replace('new QPushButton("Import public-key.json")','new QPushButton("Choose public identity file…")').replace('layout->addWidget(trust);','layout->addWidget(trust);auto *help=new QLabel("Skip this for ordinary pairing. To recognise the same identity on another phone, restore your password-protected identity backup on that phone first. OBS only needs its public identity file or code; never your private key or backup password.");help->setWordWrap(true);layout->addWidget(help);'));
await edit('android/app/src/main/java/org/clappa/app/MainActivity.kt',s=>s.replace('Text("Signing identity"','Text("Your identity"').replace('Your private signing key stays on this phone. Import a password-protected P-256 PKCS#12 file to use your own portable identity.','This code lets others recognise your signed proofs. No account is needed. To reuse your own identity on this phone, restore its password-protected backup. Your private key stays on the phone. Supported backup: P-256 PKCS#12 (.p12).').replace('Import identity (.p12)','Restore identity backup').replace('Import signing identity','Restore your identity').replace('Enter the password for your P-256 PKCS#12 file. Your existing identity is retained; this identity will sign future sessions.','Enter your backup password. This identity will sign future recordings. Existing recordings keep their original signatures.'));
await edit('android/app/build.gradle.kts',s=>s.replace('versionCode = 10','versionCode = 11').replace('0.3.0-test8','0.3.0-test9'));
console.log('Review 9 changes applied.');
