import fs from 'node:fs/promises';
const dir='docs/review9';
await fs.copyFile('output/qr-test9/results.json',dir+'/qr-recovery.json');
await fs.copyFile('output/native-integration-result.json',dir+'/native-integration.json');
await fs.copyFile('docs/test9.md',dir+'/BUILD-NOTES.md');
const qr=JSON.parse(await fs.readFile(dir+'/qr-recovery.json')),flow=JSON.parse(await fs.readFile(dir+'/emulator-flow-result.json'));
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CLAPPA · Test9 review and builds</title><style>
:root{color-scheme:dark;font:17px/1.6 system-ui;color:#f3f0e7;background:#191918}*{box-sizing:border-box}body{margin:0}main{max-width:1160px;margin:auto;padding:48px 24px 72px}h1{font-size:clamp(32px,5vw,58px);line-height:1.1;letter-spacing:-.04em;margin:14px 0 24px}h2{font-size:28px;margin:44px 0 12px}h3{font-size:19px}p{max-width:850px;color:#d1d0c5}.tag{color:#b8d1bf;font-size:13px;letter-spacing:.12em;text-transform:uppercase}.links{display:flex;flex-wrap:wrap;gap:12px;margin:24px 0}a{color:#d0e7d5;text-underline-offset:4px}.button{display:inline-block;padding:12px 18px;background:#efebdf;color:#24241e;border-radius:7px;text-decoration:none;font-weight:650}.panel{background:#282824;border:1px solid #42423b;border-radius:12px;padding:24px;margin:22px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.grid>div{min-width:0}img,video{max-width:100%;height:auto;border-radius:6px}video{width:100%;background:#111}table{border-collapse:collapse;width:100%;font-size:15px}td,th{text-align:left;padding:10px;border-bottom:1px solid #45453d}.note{font-size:14px;color:#b9b8ab}.phone{max-height:650px;display:block;margin:auto}.thumbs{display:flex;gap:12px;overflow:auto}.thumbs a{min-width:165px;max-width:220px}.thumbs img{max-height:340px}summary{cursor:pointer;padding:12px 0}@media(max-width:740px){.grid{grid-template-columns:1fr}main{padding:28px 16px}.panel{padding:16px}}@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto}}
</style><main><div class="tag">Built and checked locally · 16 September 2026</div><h1>Clearer evidence.<br>A verified link to the recording.</h1><p>Test9 implements the first priority changes from the critical review. The aim stays the same: let a viewer compare a fresh challenge, the phone photos and the scene on the other camera. These are native build captures, not a browser recreation of the app.</p>
<div class="links"><a class="button" href="builds/CLAPPA-0.3.0-test9.apk" download>Android APK</a><a class="button" href="builds/CLAPPA-test9-kit.zip" download>OBS + local verifier kit</a><a href="BUILD-NOTES.md">Installation and build notes</a><a href="builds/build.json">Build hashes</a></div>
<div class="panel"><strong>Implemented and verified</strong><ul><li>QR proof now carries the signed challenge and a phone-signed cumulative media boundary.</li><li>Original H.264/AAC Matroska packets are compared with the signed packet history.</li><li>Finishing two proof recordings left the simultaneous local broadcast running.</li><li>Larger photo, separate prompt and timestamp rows, no OBS mascot, and a smoother 310 ms entrance.</li><li>Identity setup now explains public identity codes and private backups.</li></ul><p class="note">Exact comparison needs the original recording and proof folder. QR recovery from a platform transcode transports signed evidence; it does not reproduce original packet hashes. This build has no measured AI-attack success rate.</p></div>
<h2>OBS: the actual native render</h2><p>The photo aperture is 73% larger. The QR keeps its full 292-pixel square, fixed four-module quiet zone and integer modules. The signed prompt, snapshot time and wordmark have reserved space.</p><img src="obs-camera-proof.png" alt="Native OBS proof panel with photo, QR, selfie prompt, timestamp and CLAPPA wordmark"><p class="note">The deliberately simple face and room are the Android emulator's camera scene. The displayed image is its original capture; the QR carries separate compact derivatives.</p><video controls playsinline preload="metadata" poster="obs-camera-proof.png" src="obs-motion.mp4"></video><p class="note">Recorded OBS output. Both images and QR are mounted from entrance through exit; QR updates only while the board is settled. Source size is still 872 × 480.</p>
<h2>Native Android</h2><p>The current board, safe-area layout and whole-sprite guide are retained. This pass changes identity wording and the signed media context. The portrait action and guide remain too separated; compact landscape can require scrolling for the temporary extra-photo action. Those are recorded for the next layout pass.</p><div class="grid"><div class="panel"><h3>Portrait challenge</h3><img class="phone" src="portrait-challenge.png" alt="Native Android portrait challenge"></div><div class="panel"><h3>Landscape challenge</h3><img src="landscape-challenge.png" alt="Native Android landscape challenge"><h3>Capture screen</h3><img class="phone" src="flow-camera.png" alt="Native camera with safe-area branded header and shutter"></div></div><details><summary>All twelve native state captures</summary><a href="portrait-states.png"><img src="portrait-states.png" alt="Six portrait states"></a><a href="landscape-states.png"><img src="landscape-states.png" alt="Six landscape states"></a></details><details><summary>Enlarged text, cutout and three-button navigation</summary><div class="thumbs">${['portrait','landscape','landscape-reverse'].map(o=>`<a href="stress-${o}-challenge.png"><img src="stress-${o}-challenge.png" alt="${o} challenge with enlarged text and navigation controls"></a>`).join('')}</div></details><details><summary>Native phone motion</summary><video controls playsinline preload="none" src="phone-motion.mp4"></video></details>
<h2>Checks completed here</h2><div class="panel"><table><tr><th>Check</th><th>Result</th></tr><tr><td>Protocol and verifier regression cases</td><td>33 passed</td></tr><tr><td>Android unit tests</td><td>10 passed</td></tr><tr><td>Emulator camera → OBS → final seal</td><td>${flow.result.status}</td></tr><tr><td>Actual original recording packets</td><td>${flow.result.media_binding.packets.toLocaleString()} matched</td></tr><tr><td>Signed prefixes transplanted onto changed scene content</td><td>Both rejected</td></tr><tr><td>Two recording sessions during one local broadcast</td><td>Both sealed; broadcast stayed live</td></tr>${qr.reports.map(r=>`<tr><td>Local QR recovery · ${r.name}</td><td>${r.recoveredEvents}/${r.expectedEvents} complete events</td></tr>`).join('')}</table><p class="note">Camera payload: 14 chunks per event, two compact photos plus signed context. Tile: 872 × 480 on a 1920 × 1080 scene. 1080p/720p used x264 CRF23; 480p/360p used CRF28; blur was sigma 0.6. This is local re-encoding, not Twitch/YouTube certification. Native camera checks use an emulator, not physical flash measurements.</p><div class="links"><a href="prefix-results.json">Prefix checks</a><a href="emulator-flow-result.json">Camera flow</a><a href="qr-recovery.json">Recovery measurements</a><a href="stream-lifecycle.json">Broadcast continuity</a><a href="MEDIA-PROFILE.md">Exact media profile</a></div></div>
<h2>Next work, in order</h2><ol><li>Unify the phone's prompt, mascot and capture action into one measured interaction region, including compact landscape and large text.</li><li>Add a viewer-facing import and comparison screen: challenge, A/B photos, timing and original-media match together.</li><li>Complete output-start/reconnect behaviour and long-recording storage limits. Stream-first operation is supported; starting streaming during an existing proof recording still invalidates that session.</li><li>Implement overlapping two-camera challenges and run current fast-synthesis attacks against them, keeping engineering evaluation here rather than assigning it to the owner.</li></ol><p><a href="../critical-review/index.html">Full critical review and recommendations</a></p><p class="note">No cap! Clap!!</p></main></html>`;
await fs.writeFile(dir+'/index.html',html);
await fs.cp(dir,'docs/review7/revision9',{recursive:true});
await fs.writeFile('docs/review7/index.html','<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/revision9/index.html"><title>CLAPPA review</title><a href="/revision9/index.html">Open Test9 builds and review</a>');
let review=await fs.readFile('docs/review7/critical-review/index.html','utf8');if(!review.includes('Test9 implementation is available'))review=review.replace(/<body[^>]*>/,m=>m+'<div style="padding:18px 24px;background:#dce7d6;color:#20291c;font:16px system-ui">Test9 implementation is available. <a style="color:inherit" href="/revision9/index.html">Open the builds, native captures and completed checks</a>. The findings below describe the earlier Test8 baseline.</div>');await fs.writeFile('docs/review7/critical-review/index.html',review);
console.log('Published http://127.0.0.1:17450/revision9/index.html');

await import("./publish-beacon-correction.mjs");
