import fs from 'node:fs/promises';
const dir='docs/review8';
const old=await fs.readFile('docs/review7/index-test7.html','utf8').catch(()=>fs.readFile('docs/review7/index.html','utf8'));
const style=old.match(/<style>[\s\S]*?<\/style>/)[0];
const flow=JSON.parse(await fs.readFile(dir+'/emulator-flow-result.json'));
const qr=JSON.parse(await fs.readFile(dir+'/qr-camera-results.json'));
const tls=JSON.parse(await fs.readFile(dir+'/tls-results.json'));
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CLAPPA · Test8 native review</title>${style}<main>
<header><div class="tag">Native build review · Test8</div><h1><em>CLAPPA</em> / paired sticks</h1><p>Opposed chevrons, a fixed lower stick, contact shadow and a three-screw plate that reaches its base. The phone and OBS use the same construction.</p><div class="actions"><a class="download" href="builds/CLAPPA-0.3.0-test8.apk" download>Download Android APK</a><a class="download" href="builds/CLAPPA-test8-kit.zip" download>Download OBS + test kit</a><a href="testing.html">Install &amp; test notes</a></div><p><strong>OBS source is now 872 × 480.</strong> Reposition it after updating. On a 1920 × 1080 canvas, use X 1040 / Y 592 at scale 1 to keep it fully visible.</p></header>
<section><h2>The actual OBS board</h2><p>The two media mounts have their own space above a dedicated digital timestamp and logo footer. The tail has a broader brush shape and curls around the left edge.</p><div class="card"><a href="obs-camera-proof.png"><img src="obs-camera-proof.png" alt="Actual OBS board showing paired chevron sticks, full-size QR, photo and separate footer"></a><video controls playsinline preload="metadata" poster="obs-camera-proof.png" src="obs-motion.mp4"></video><p class="note">Actual OBS recording with emulator-camera photos. Both photos are attached from entry; the QR advances only while the board is stationary. The patterned scene is the emulator camera's image.</p><details><summary>Full stream canvas</summary><img src="obs-full-scene.png" alt="Full 1920 by 1080 OBS output"></details><details><summary>Motion contact sheet</summary><img src="obs-motion-sheet.png" alt="Twenty frames showing entrance, stationary proof and exit"></details><details><summary>Distinct Photo B → Photo A fixture</summary><div class="columns"><img src="obs-flash-fixture.png" alt="Photo B visible at entry"><img src="obs-fixture.png" alt="Photo A visible after crossfade"></div></details></div></section>
<section><h2>Native Android layout</h2><p>A bounded charcoal slate with a restrained bevel and shadow, a solid gear, and the same matched sticks. The possum still rises from the bottom of the phone.</p><div class="columns"><div class="card"><div class="switches" id="orientations"><button aria-pressed="true" data-o="portrait">Portrait</button><button aria-pressed="false" data-o="landscape">Landscape</button></div><div class="switches" id="states"><button data-s="unpaired">Unpaired</button><button data-s="standby">Connected</button><button aria-pressed="true" data-s="ready">Ready</button><button data-s="challenge">Prompt</button><button data-s="sent">Sent</button><button data-s="lost">Reconnect</button></div><div class="viewer"><img id="phone" src="portrait-ready.png" alt="Native Android portrait ready screen"></div><p class="note">Screenshots of the production Compose component running in the separate review APK, with the same assets and layout code as the downloadable build.</p></div><div class="card phone"><h3>Actual phone motion</h3><video controls playsinline preload="metadata" poster="portrait-ready.png" src="phone-motion.mp4"></video><p class="note">Native screen recording: one snap, impact settle and whole-sprite guide entrance. Silent recording; listen to the audio samples below.</p></div></div></section>
<section><h2>120 and approximately 135 BPM</h2><p>The same phrase and pitches at two speeds, rendered by the app's compiled audio engine using the approved real clapperboard strike. New challenges select either speed.</p><div class="columns"><div class="card"><h3>120 BPM</h3><audio controls preload="none" src="riff-120.wav"></audio></div><div class="card"><h3>≈135 BPM</h3><audio controls preload="none" src="riff-135.wav"></audio></div></div><p class="note">The signed integer-millisecond grid gives 135.135 BPM. Six or seven hits, anchored beats and a pentatonic contour. <a href="https://bigsoundbank.com/clapperboard-s1011.html">CC0 source: Joseph SARDIN.</a></p></section>
<section><h2>System edges and larger text</h2><div class="card"><img src="stress-landscape-challenge.png" alt="Landscape at 130 percent text with three-button navigation and a simulated cutout"><p class="note">130% text and a narrower logical screen, with three-button navigation and simulated camera cutout. The control column and speech bubble have separate space.</p><details><summary>Portrait and reverse landscape</summary><div class="viewer"><img src="stress-portrait-challenge.png" alt="Portrait at 130 percent text"></div><img src="stress-landscape-reverse-challenge.png" alt="Reverse landscape at 130 percent text"></details></div></section>
<section><h2>Verification from this revision</h2><div class="card"><table><thead><tr><th>Check</th><th>Result</th></tr></thead><tbody><tr><td>Native Android → camera → OBS → final seal</td><td class="pass">${flow.result.status}</td></tr><tr><td>Two photo-pair save-completion gaps</td><td>${flow.captures.map(c=>c.gapMs+' ms').join(' / ')}</td></tr><tr><td>TLS 1.3 concurrency probe</td><td class="pass">${tls.completed} requests / ${tls.concurrentClients} simultaneous clients; pins checked, unauthorized requests rejected</td></tr>${qr.reports.map(r=>`<tr><td>Local QR re-encode: ${r.name}</td><td class="${r.recoveredEvents===2?'pass':'limited'}">${r.recoveredEvents} / ${r.expectedEvents} full photo events recovered</td></tr>`).join('')}</tbody></table><p class="note">Local tests used Android 15 and an isolated Windows OBS installation. They do not certify physical phone illumination or a Twitch/YouTube platform round trip. The timestamp records photo save completion. Independent matching of packet archives to muxed recordings remains unfinished.</p><div class="actions"><a href="validation.json">Test results</a><a href="qr-camera-results.json">QR measurements</a><a href="tls-results.json">Connection probe</a><a href="builds/build.json">Build hashes</a></div></div></section>
<footer>No cap! Clap!!</footer></main><script>let orientation='portrait',state='ready';function update(){document.querySelector('#phone').src=orientation+'-'+state+'.png';document.querySelector('#phone').alt='Native Android '+orientation+' '+state;document.querySelectorAll('[data-o]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.o===orientation));document.querySelectorAll('[data-s]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.s===state))}document.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>{orientation=b.dataset.o;update()});document.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>{state=b.dataset.s;update()});update()</script></html>`;
await fs.writeFile(dir+'/index.html',html);
// Preserve Test7 and the established URL. Publish only after all evidence exists.
await fs.cp(dir,'docs/review7/revision8',{recursive:true});
try{await fs.access('docs/review7/index-test7.html')}catch{await fs.copyFile('docs/review7/index.html','docs/review7/index-test7.html')}
await fs.writeFile('docs/review7/index.html','<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=revision8/index.html"><title>CLAPPA review</title><a href="revision8/index.html">Open the latest CLAPPA review</a>');
console.log('Published Test8 evidence at http://127.0.0.1:17450/revision8/index.html');
