import fs from 'node:fs';const file='android/app/src/main/java/org/clappa/app/MainActivity.kt';let s=fs.readFileSync(file,'utf8');
function r(a,b){if(!s.includes(a))throw Error('Missing '+a.slice(0,80));s=s.replaceAll(a,b)}
r('private var responseTimer:Job?=null','private var responseTimer:Job?=null\n    private var issueJob:Job?=null\n    private var captureJob:Job?=null\n    private val savePublicIdentity=registerForActivityResult(ActivityResultContracts.CreateDocument("application/json")){uri->if(uri!=null)lifecycleScope.launch{try{withContext(Dispatchers.IO){contentResolver.openOutputStream(uri)!!.use{it.write(Proof.canonical(Proof.publicKey()).toByteArray())}};connectionNotice="Public identity saved. It contains no private key and is safe to share."}catch(e:Exception){connectionNotice="Could not save public identity. Try another folder."}}}');
r('"seal-request"->{obsRecording=false;pendingSeal=m;phase=BoardPhase.ENDING;status="Recording closed — confirm the final seal"}', '"seal-request"->{obsRecording=false;phase=BoardPhase.ENDING;status="Signing the closed recording…";withContext(Dispatchers.IO){checkNotNull(session).seal(m)}}\n        "recording-closed"->{obsRecording=false;issueJob?.cancelAndJoin();captureJob?.cancelAndJoin();responseTimer?.cancel();claimTimer?.cancel();cameraOpen=false;claimMode=false;claimSeconds=0;prompt="";phase=BoardPhase.ENDING;status="Finishing the signed transcript…";withContext(Dispatchers.IO){session?.let{if(!it.ended){it.fail("cancelled");it.finish(alreadyClosed=true)}}}}');
r('session!!.lastSuccessAt+6000','session!!.lastSuccessAt+30000');
r('if(busy||s.pending!=null||s.ended||s.hadFailure)return','if(busy||s.pending!=null||s.ended)return');
r('lifecycleScope.launch {try {\n            val round=', 'issueJob=lifecycleScope.launch {try {\n            val round=');
r('phase=BoardPhase.INCOMPLETE\n                        status="Time ran out. This recording remains incomplete.";', 'phase=BoardPhase.READY;canFinish=s.endDone\n                        status="Time ran out. This attempt is recorded; you can continue.";');
r('}catch(e:Exception){android.util.Log.e("ClappaFreshness"', '}catch(e:CancellationException){throw e}catch(e:Exception){android.util.Log.e("ClappaFreshness"');
r('status=e.message?:"Challenge unavailable";phase=BoardPhase.INCOMPLETE', 'status="Challenge not completed. You can continue. "+(e.message?:"");phase=BoardPhase.READY;canFinish=s.endDone');
r('busy=true;lifecycleScope.launch {\n        try{\n            val selfie=', 'busy=true;captureJob=lifecycleScope.launch {\n        try{\n            val selfie=');
r('}catch(e:Exception){pendingDelivery=false;', '}catch(e:CancellationException){throw e}catch(e:Exception){pendingDelivery=false;');
r('status="Capture failed: "+(e.message?:"Camera unavailable");phase=BoardPhase.INCOMPLETE;cameraOpen=false;prompt=""', 'status="Photo not completed. You can continue. "+(e.message?:"Camera unavailable");phase=BoardPhase.READY;canFinish=s.endDone;cameraOpen=false;prompt=""');
r('busy=true;lifecycleScope.launch{try{val(f,at)=take();','busy=true;captureJob=lifecycleScope.launch{try{val(f,at)=take();');
r('}catch(e:Exception){status="Additional photo not accepted:', '}catch(e:CancellationException){throw e}catch(e:Exception){status="Additional photo not accepted:');
r('onClaim={claimMode=true;openCamera()}','onClaim={claimMode=true;openCamera()}');
const a=s.indexOf('        pendingSeal?.let{request->AlertDialog'),b=s.indexOf('\n',a);if(a<0)throw Error('seal dialog missing');s=s.slice(0,a)+s.slice(b);
r('Text("Your identity",style=MaterialTheme.typography.titleMedium)\n            androidx.compose.foundation.text.selection.SelectionContainer', 'Text("Your CLAPPA identity",style=MaterialTheme.typography.titleMedium)\n            Text("This phone signs your recordings with a private key. Its matching public identity lets viewers recognise that future proofs came from the same signer. No CLAPPA account is needed.",fontSize=13.sp)\n            Text("Public identity code · safe to share",Modifier.padding(top=12.dp),fontSize=13.sp)\n            androidx.compose.foundation.text.selection.SelectionContainer');
r('Text("This code lets others recognise your signed proofs. No account is needed. To reuse your own identity on this phone, restore its password-protected backup. Your private key stays on the phone. Supported backup: P-256 PKCS#12 (.p12).",fontSize=13.sp)', `Text("Put this public code in your Twitch About panel or another profile you control. Viewers can compare it with the identity in your proofs. Publishing it links your profile to the code; CLAPPA does not automatically verify account ownership.",fontSize=13.sp)
            TextButton(onClick={val clipboard=getSystemService(CLIPBOARD_SERVICE) as android.content.ClipboardManager;clipboard.setPrimaryClip(android.content.ClipData.newPlainText("CLAPPA public identity","CLAPPA public identity: "+identityId));connectionNotice="Public identity copied. Paste it into your profile."}){Text("Copy code for my profile")}
            TextButton(onClick={savePublicIdentity.launch("clappa-public-identity.json")}){Text("Save public identity file")}
            Text("The file contains your P-256 public key and its SHA-256 identity code. OBS and the verifier can import it. It contains no private signing key.",fontSize=13.sp)
            HorizontalDivider(Modifier.padding(vertical=12.dp))
            Text("Private signing key · keep secret",style=MaterialTheme.typography.titleSmall)
            Text("Your current private key is protected in Android's key store and cannot be exported by this app. Never put a private key or its backup on a public profile.",fontSize=13.sp)
            Text("Already have a portable identity? Import a password-protected .p12 or .pfx file containing a P-256 private key and its certificate (PKCS#12 format). Keep that original file and its password to use the same identity on another phone. Importing replaces the identity used for future recordings and requires pairing again.",fontSize=13.sp)`);
r('Text("Restore identity backup")','Text("Import an existing private key")');r('title={Text("Restore your identity")}','title={Text("Import your private identity")}');
r('"Additional photo" else prompt','"Additional photo · ${claimSeconds}s" else prompt');
fs.writeFileSync(file,s);
