import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {verifyNistPulse} from '../../protocol/nist-beacon.mjs';import {challengeSeed,choicesFromSeed,CHOICE_MAPPING} from '../../protocol/challenge-derivation.mjs';
const dir=new URL('../../test-vectors/nist/',import.meta.url),pulse=JSON.parse(fs.readFileSync(new URL('pulse.json',dir))),pem=fs.readFileSync(new URL('certificate.pem',dir),'utf8'),trust=JSON.parse(fs.readFileSync(new URL('trust.json',dir))),options={trustedCertificateSha256:[trust.certificate_sha256]};
test('archived authentic NIST signature and output verify offline',()=>assert.equal(verifyNistPulse(pulse,pem,options).pulse,1000000));
for(const field of ['timeStamp','localRandomValue','outputValue','signatureValue'])test('NIST rejects changed '+field,()=>{const p=structuredClone(pulse);p[field]=field==='timeStamp'?'2020-07-31T20:25:00.000Z':p[field].replace(/^./,p[field][0]==='A'?'B':'A');assert.throws(()=>verifyNistPulse(p,pem,options))});
test('proof-supplied certificate cannot establish its own trust',()=>{assert.throws(()=>verifyNistPulse(pulse,pem));assert.throws(()=>verifyNistPulse(pulse,pem,{trustedCertificateSha256:['00'.repeat(32)]}))});
test('wrong designated pulse and duplicate skip-list entries are rejected',()=>{assert.throws(()=>verifyNistPulse(pulse,pem,{...options,expectedPulse:pulse.pulseIndex+1}));const p=structuredClone(pulse);p.listValues[1]=p.listValues[0];assert.throws(()=>verifyNistPulse(p,pem,options))});
test('all response choices reproduce from committed context and verified pulse',()=>{const v=verifyNistPulse(pulse,pem,options),c={mapping:CHOICE_MAPPING,pulse:{chain:v.chain,index:v.pulse,at:v.at},media_head:'aa'.repeat(32)},seed=challengeSeed(c,v);assert.deepEqual(choicesFromSeed(seed),choicesFromSeed(challengeSeed(c,v)));assert.notEqual(seed,challengeSeed({...c,media_head:'bb'.repeat(32)},v));assert.throws(()=>challengeSeed({...c,pulse:{...c.pulse,index:v.pulse+1}},v));});
test('mapped phrases have six/seven hits, anchored beats, valid pitches and resolved ending',()=>{for(let n=0;n<100;n++){const c=choicesFromSeed(n.toString(16).padStart(64,'0'));assert.ok([6,7].includes(c.pitches.length));assert.equal(c.pitches.length,[...c.cadence].filter(x=>x==='1').length);for(const j of [0,4,8,12])assert.equal(c.cadence[j],'1');assert.equal(c.pitches.at(-1),0);assert.ok(c.pitches.every(p=>[-5,-3,0,2,4,7].includes(p)));assert.equal(c.camera==='rear',c.flash==='led');}});
