import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {verifyBundle,hashObject} from '../proof.mjs';import {deterministicSign as sign} from '../../test-vectors/generate.mjs';
async function fixture(t,mutate,policy=true){const prefix=path.join(os.tmpdir(),'clappa-session-v2-');const dir=await fs.mkdtemp(prefix);t.after(async()=>{if(!dir.startsWith(prefix))throw Error('Unexpected cleanup path');await fs.rm(dir,{recursive:true,force:true})});await fs.cp(new URL('../../test-vectors/valid/',import.meta.url),dir+'/proof',{recursive:true});await fs.cp(new URL('../../test-vectors/recording.bin',import.meta.url),dir+'/recording.bin');const names=(await fs.readdir(dir+'/proof/events')).sort();let events=await Promise.all(names.map(async n=>JSON.parse(await fs.readFile(dir+'/proof/events/'+n)).payload));if(policy)Object.assign(events[0].data,{session_policy:'CLAPPA-SESSION-v2',claim_window_ms:30000});if(policy)for(const e of events)if(e.type==='challenge-issued')e.data.pair_window_ms=3000;events=mutate(events);for(const n of names)await fs.unlink(dir+'/proof/events/'+n);let prev=null;for(let i=0;i<events.length;i++){const e=sign({...events[i],seq:i,prev});prev=hashObject(e);await fs.writeFile(dir+'/proof/events/'+String(i).padStart(6,'0')+'.json',JSON.stringify(e))}const seal=JSON.parse(await fs.readFile(dir+'/proof/final-seal.json'));Object.assign(seal.payload,{head:prev,event_count:events.length,at:events.at(-1).at+100});await fs.writeFile(dir+'/proof/final-seal.json',JSON.stringify(sign(seal.payload)));return verifyBundle(dir+'/proof',dir+'/recording.bin')}
const failedStart=events=>events.filter((e,i)=>i!==3).map((e,i)=>i===2?{...e,type:'challenge-failed',data:{challenge_id:e.data.challenge_id,reason:'timeout'}}:e);
test('session v2 seals a missed challenge and subsequent completed response, reporting the miss',async t=>{const r=await fixture(t,failedStart);assert.equal(r.status,'EXACT ORIGINAL VERIFIED');assert.equal(r.missed_challenges.length,1);assert.equal(r.missed_challenges[0].reason,'timeout')});
test('legacy sessions retain their previous strict interpretation',async t=>assert.notEqual((await fixture(t,failedStart,false)).status,'EXACT ORIGINAL VERIFIED'));
function delayedClaim(delay){return events=>events.map((e,i)=>i<3?e:{...e,at:e.at+delay,data:{...e.data,...(i===3?{captured_at:e.data.captured_at+delay}:{}),...(i===5?{a_at:e.data.a_at+delay,b_at:e.data.b_at+delay}:{})}})}
test('extra photo at twenty seconds is accepted under signed v2 policy',async t=>assert.equal((await fixture(t,delayedClaim(20000))).status,'EXACT ORIGINAL VERIFIED'));
test('extra photo beyond thirty seconds is rejected',async t=>assert.equal((await fixture(t,delayedClaim(31000))).status,'INVALID PROOF'));
test('external stop can seal integrity while explicitly reporting absent challenge bookends',async t=>{const r=await fixture(t,e=>[e[0],e[6]]);assert.equal(r.status,'EXACT ORIGINAL VERIFIED');assert.deepEqual(r.bookends,{start_resolved:false,end_resolved:false});assert.equal(r.timed_responses,0)});
test('a pending challenge cannot silently disappear at session end',async t=>assert.equal((await fixture(t,e=>[e[0],e[1],e[6]])).status,'INVALID PROOF'));
